/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tutela.modulos.principal.visoes;

import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import tutela.modulos.cadastros.visoes.CriancaBusca;
import tutela.modulos.cadastros.visoes.OcorrenciaBusca;
import tutela.modulos.cadastros.visoes.PessoaBusca;

/**
 *
 * @author augusto
 */
public class Sistema extends javax.swing.JFrame {

    /**
     * Creates new form Sistema
     */
    public Sistema() 
    {
        initComponents();
        
        // Seta propriedades para a toolbar
       // toolbarNovo.setIcon(new ImageIcon(Sistema.this.getClass().getResource("/tutela/publico/imagens/nova_ocorrencia.png")));
        
        // Seta propriedades para o menu principal.
        menu.add(Box.createRigidArea(new Dimension(100, 40)));
        //menuPrincipal.setIcon(new ImageIcon(Sistema.this.getClass().getResource("/tutela/publico/imagens/principal.png")));
        menuCadastros.setIcon(new ImageIcon(Sistema.this.getClass().getResource("/tutela/publico/imagens/cadastros.png")));
        menuProcessos.setIcon(new ImageIcon(Sistema.this.getClass().getResource("/tutela/publico/imagens/processos.png")));
        
        menuConfiguracoes.setIcon(new ImageIcon(Sistema.this.getClass().getResource("/tutela/publico/imagens/configuracoes.png")));
        logout.setIcon(new ImageIcon(Sistema.this.getClass().getResource("/tutela/publico/imagens/logout.png")));
        
        // Seta propriedades para os submenus.
        menuOcorrencias.add(Box.createRigidArea(new Dimension(200, 50)));
        menuOcorrencias.setIcon(new ImageIcon(Sistema.this.getClass().getResource("/tutela/publico/imagens/ocorrencias.png")));
        menuConselheiros.add(Box.createRigidArea(new Dimension(200, 50)));
        menuConselheiros.setIcon(new ImageIcon(Sistema.this.getClass().getResource("/tutela/publico/imagens/conselheiros.png")));
        menuCriancas.add(Box.createRigidArea(new Dimension(200, 50)));
        menuCriancas.setIcon(new ImageIcon(Sistema.this.getClass().getResource("/tutela/publico/imagens/criancas.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelConteudo = new javax.swing.JPanel();
        menu = new javax.swing.JMenuBar();
        menuCadastros = new javax.swing.JMenu();
        menuConselheiros = new javax.swing.JMenuItem();
        menuCriancas = new javax.swing.JMenuItem();
        menuProcessos = new javax.swing.JMenu();
        menuOcorrencias = new javax.swing.JMenuItem();
        menuConfiguracoes = new javax.swing.JMenu();
        logout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.SystemColor.controlLtHighlight);

        panelConteudo.setBackground(java.awt.SystemColor.controlLtHighlight);

        javax.swing.GroupLayout panelConteudoLayout = new javax.swing.GroupLayout(panelConteudo);
        panelConteudo.setLayout(panelConteudoLayout);
        panelConteudoLayout.setHorizontalGroup(
            panelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1044, Short.MAX_VALUE)
        );
        panelConteudoLayout.setVerticalGroup(
            panelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelConteudo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelConteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menu.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N

        menuCadastros.setText("Cadastros");

        menuConselheiros.setText("Pessoas");
        menuConselheiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConselheirosActionPerformed(evt);
            }
        });
        menuCadastros.add(menuConselheiros);

        menuCriancas.setText("Crianças/Adolescentes");
        menuCriancas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCriancasActionPerformed(evt);
            }
        });
        menuCadastros.add(menuCriancas);

        menu.add(menuCadastros);

        menuProcessos.setText("Processos");

        menuOcorrencias.setText("Ocorrências");
        menuOcorrencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOcorrenciasActionPerformed(evt);
            }
        });
        menuProcessos.add(menuOcorrencias);

        menu.add(menuProcessos);

        menuConfiguracoes.setText("Configurações");

        logout.setText("Efetuar logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        menuConfiguracoes.add(logout);

        menu.add(menuConfiguracoes);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuOcorrenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOcorrenciasActionPerformed
        OcorrenciaBusca ocorrenciaVisao = new OcorrenciaBusca();
        panelConteudo.removeAll();
        panelConteudo.add(ocorrenciaVisao);
        
        try 
        {
            ocorrenciaVisao.setMaximum(true);
        } 
        catch (PropertyVetoException ex) 
        {
            Logger.getLogger(Sistema.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        ocorrenciaVisao.setVisible(true);
    }//GEN-LAST:event_menuOcorrenciasActionPerformed

    private void menuCriancasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCriancasActionPerformed
        CriancaBusca criancaVisao = new CriancaBusca(); 
        panelConteudo.removeAll();
        panelConteudo.add(criancaVisao);
        
        try 
        {
            criancaVisao.setMaximum(true);
        } 
        catch (PropertyVetoException ex) 
        {
            Logger.getLogger(Sistema.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        criancaVisao.setVisible(true);
    }//GEN-LAST:event_menuCriancasActionPerformed

    private void menuConselheirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConselheirosActionPerformed
        PessoaBusca pessoaVisao = new PessoaBusca(); 
        panelConteudo.removeAll();
        panelConteudo.add(pessoaVisao);
        
        try 
        {
            pessoaVisao.setMaximum(true);
        } 
        catch (PropertyVetoException ex) 
        {
            Logger.getLogger(Sistema.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        pessoaVisao.setVisible(true);
    }//GEN-LAST:event_menuConselheirosActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "Você têm certeza que deseja sair do sistema?", "Atenção!", JOptionPane.YES_NO_OPTION);
            
        if ( reply == JOptionPane.YES_OPTION ) 
        {
            Login login = new Login();
            login.setLocationRelativeTo(null);
            login.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenu menuConfiguracoes;
    private javax.swing.JMenuItem menuConselheiros;
    private javax.swing.JMenuItem menuCriancas;
    private javax.swing.JMenuItem menuOcorrencias;
    private javax.swing.JMenu menuProcessos;
    private javax.swing.JPanel panelConteudo;
    // End of variables declaration//GEN-END:variables
}
