/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tutela.modulos.cadastros.visoes;

import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import tutela.modulos.cadastros.modelos.daos.PessoaDAO;
import tutela.modulos.cadastros.modelos.negocios.Crianca;
import tutela.modulos.cadastros.modelos.negocios.Pessoa;

/**
 *
 * @author augusto
 */
public class PessoaBusca extends javax.swing.JInternalFrame {

    public static PessoaFormulario pessoaFormulario;
    
    /**
     * Creates new form PessoaBusca
     */
    public PessoaBusca() {
        super();
        initComponents();
        
        setTitle("Pessoas");
        
        botaoNovo.setIcon(new ImageIcon(PessoaBusca.this.getClass().getResource("/tutela/publico/imagens/novo.png")));
        botaoEditar.setIcon(new ImageIcon(PessoaBusca.this.getClass().getResource("/tutela/publico/imagens/editar.png")));
        botaoExcluir.setIcon(new ImageIcon(PessoaBusca.this.getClass().getResource("/tutela/publico/imagens/excluir.png")));
        botaoBuscar.setIcon(new ImageIcon(PessoaBusca.this.getClass().getResource("/tutela/publico/imagens/buscar.png")));
        botaoAtualizar.setIcon(new ImageIcon(PessoaBusca.this.getClass().getResource("/tutela/publico/imagens/atualizar.png")));
        
        this.desabilitaAcoesDeEdicaoEExclusao();
    
        tabelaPessoa.setRowHeight(20);
        tabelaPessoa.setPreferredSize(new Dimension(10000, 500));
        
        // Evento ao selecionar um item da tabela.
        tabelaPessoa.getSelectionModel().addListSelectionListener(new ListSelectionListener() {  
            @Override  
            public void valueChanged(ListSelectionEvent evt) {  
               if (evt.getValueIsAdjusting())  
               {
                   return;  
               }
               
               int selected = tabelaPessoa.getSelectedRow();
               
               if ( selected != -1 )
               {
                    abilitaAcoesDeEdicaoEExclusao();
               }
               else
               {
                   desabilitaAcoesDeEdicaoEExclusao();
               }
            }  
         });
        
        this.atualizarTabela(0);
    }
    
    private void abilitaAcoesDeEdicaoEExclusao()
    {
        botaoEditar.setEnabled(true);
        botaoExcluir.setEnabled(true);
    }
    
    private void desabilitaAcoesDeEdicaoEExclusao()
    {
        botaoEditar.setEnabled(false);
        botaoExcluir.setEnabled(false);
    }
    
    public final void atualizarTabela(int codigoRegistroASelecionar) {
	Crianca pessoa = new Crianca();
        PessoaDAO pessoaDao = new PessoaDAO();
        ResultSet resultSet;
        resultSet = pessoaDao.listar(0, null);
        pessoa.populaRegistrosNaTabela(tabelaPessoa, resultSet, codigoRegistroASelecionar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        botaoNovo = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        botaoAtualizar = new javax.swing.JButton();
        painelConteudo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPessoa = new javax.swing.JTable();
        busca = new javax.swing.JTextField();
        botaoBuscar = new javax.swing.JButton();

        setBorder(null);
        setTitle("Pessoas");

        jToolBar1.setRollover(true);

        botaoNovo.setText("    Novo    ");
        botaoNovo.setFocusable(false);
        botaoNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNovoActionPerformed(evt);
            }
        });
        jToolBar1.add(botaoNovo);

        botaoEditar.setText("   Editar   ");
        botaoEditar.setFocusable(false);
        botaoEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });
        jToolBar1.add(botaoEditar);

        botaoExcluir.setText("   Excluir  ");
        botaoExcluir.setFocusable(false);
        botaoExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });
        jToolBar1.add(botaoExcluir);

        botaoAtualizar.setText(" Atualizar ");
        botaoAtualizar.setFocusable(false);
        botaoAtualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoAtualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizarActionPerformed(evt);
            }
        });
        jToolBar1.add(botaoAtualizar);

        painelConteudo.setBackground(java.awt.SystemColor.controlLtHighlight);

        tabelaPessoa.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        tabelaPessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Estado civil", "Data de nascimento", "Sexo", "Origem étnica", "Cidade", "Telefone celular", "É conselheiro?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaPessoa);

        busca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscaKeyPressed(evt);
            }
        });

        botaoBuscar.setText("Procurar");
        botaoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarActionPerformed(evt);
            }
        });
        botaoBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botaoBuscarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout painelConteudoLayout = new javax.swing.GroupLayout(painelConteudo);
        painelConteudo.setLayout(painelConteudoLayout);
        painelConteudoLayout.setHorizontalGroup(
            painelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConteudoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1002, Short.MAX_VALUE)
                    .addGroup(painelConteudoLayout.createSequentialGroup()
                        .addComponent(busca, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelConteudoLayout.setVerticalGroup(
            painelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelConteudoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(busca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelConteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovoActionPerformed
        pessoaFormulario = new PessoaFormulario(this, true);
        pessoaFormulario.setLocationRelativeTo(null);  // centraliza a tela
        pessoaFormulario.setVisible(true);
    }//GEN-LAST:event_botaoNovoActionPerformed

    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarActionPerformed
        int selected = tabelaPessoa.getSelectedRow();

        if ( selected != -1 )
        {
            Object registro = tabelaPessoa.getValueAt(selected, 0);
            int codPessoa = Integer.parseInt(registro.toString());

            Pessoa pessoa = new Pessoa(codPessoa);

            pessoaFormulario = new PessoaFormulario(this, true);
            pessoaFormulario.populaForumlario(pessoa);
            pessoaFormulario.setLocationRelativeTo(null);
            pessoaFormulario.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Selecione um registro!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botaoEditarActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        int selected = tabelaPessoa.getSelectedRow();

        if ( selected != -1 )
        {
            int reply = JOptionPane.showConfirmDialog(null, "Você têm certeza que deseja excluir este registro?", "Atenção!", JOptionPane.YES_NO_OPTION);

            if ( reply == JOptionPane.YES_OPTION )
            {
                Object registro = tabelaPessoa.getValueAt(selected, 0);
                int idPessoa = Integer.parseInt(registro.toString());

                PessoaDAO pessoaDao = new PessoaDAO();

                if ( pessoaDao.excluir(idPessoa) )
                {
                    this.atualizarTabela(0);
                    JOptionPane.showMessageDialog(null, "Registro excluído com sucesso!");
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Selecione um registro!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void botaoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizarActionPerformed
        this.atualizarTabela(0);
    }//GEN-LAST:event_botaoAtualizarActionPerformed

    private void buscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscaKeyPressed
        if ( evt.getKeyCode() == KeyEvent.VK_ENTER )
        {
            this.botaoBuscarActionPerformed(null);
        }
    }//GEN-LAST:event_buscaKeyPressed

    private void botaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarActionPerformed
        String buscar = this.busca.getText();
        Crianca pessoa = new Crianca();
        PessoaDAO pessoaDao = new PessoaDAO();
        ResultSet resultSet;
        resultSet = pessoaDao.listar(0, buscar);
        pessoa.populaRegistrosNaTabela(tabelaPessoa, resultSet, 0);
    }//GEN-LAST:event_botaoBuscarActionPerformed

    private void botaoBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botaoBuscarKeyPressed
        if ( evt.getKeyCode() == KeyEvent.VK_ENTER )
        {
            this.botaoBuscarActionPerformed(null);
        }
    }//GEN-LAST:event_botaoBuscarKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAtualizar;
    private javax.swing.JButton botaoBuscar;
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoNovo;
    private javax.swing.JTextField busca;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel painelConteudo;
    private javax.swing.JTable tabelaPessoa;
    // End of variables declaration//GEN-END:variables
}
